=== Insightfuturesbr/Insight-alpha-/contracts/jsonschema/ciclos_drawdown.v1.json
{
  "$schema":"https://json-schema.org/draft/2020-12/schema",
  "title":"CiclosDrawdownV1",
  "type":"array",
  "items":{
    "type":"object",
    "required":[
      "ID Ciclo","Data Início","Data Fim","Duração do Ciclo",
      "Máxima Dívida do Ciclo","Média Máximas Até o Ciclo","Percentil 75 Máximas Até o Ciclo",
      "ops_declinio_total","emprestimos_declinio","amortizacoes_declinio","lucros_declinio",
      "ops_recuperacao_total","emprestimos_recuperacao","amortizacoes_recuperacao","lucros_recuperacao"
    ],
    "properties":{
      "ID Ciclo":{"type":"integer","minimum":1},
      "Data Início":{"type":"string"},
      "Data Fim":{"type":"string"},
      "Duração do Ciclo":{"type":"string"},
      "Máxima Dívida do Ciclo":{"type":"number"},
      "Média Máximas Até o Ciclo":{"type":"number"},
      "Percentil 75 Máximas Até o Ciclo":{"type":"number"},
      "ops_declinio_total":{"type":"integer","minimum":0},
      "emprestimos_declinio":{"type":"integer","minimum":0},
      "amortizacoes_declinio":{"type":"integer","minimum":0},
      "lucros_declinio":{"type":"integer","minimum":0},
      "ops_recuperacao_total":{"type":"integer","minimum":0},
      "emprestimos_recuperacao":{"type":"integer","minimum":0},
      "amortizacoes_recuperacao":{"type":"integer","minimum":0},
      "lucros_recuperacao":{"type":"integer","minimum":0}
    },
    "additionalProperties":false
  }
}

=== Insightfuturesbr/Insight-alpha-/temp/drawdown/ciclos_drawdown.json
[{"ID Ciclo":1,"Data In\u00edcio":"2023-01-02 09:48:00","Data Fim":"2023-01-02 10:47:00","Dura\u00e7\u00e3o do Ciclo":"59min","M\u00e1xima D\u00edvida do Ciclo":-378.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":0.0,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":0.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":2,"Data In\u00edcio":"2023-01-02 11:05:00","Data Fim":"2023-01-02 12:33:00","Dura\u00e7\u00e3o do Ciclo":"1h 28min","M\u00e1xima D\u00edvida do Ciclo":-274.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-378.0,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-378.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":3,"Data In\u00edcio":"2023-01-02 12:48:00","Data Fim":"2023-01-02 14:53:00","Dura\u00e7\u00e3o do Ciclo":"2h 5min","M\u00e1xima D\u00edvida do Ciclo":-280.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-326.0,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-352.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":4,"Data In\u00edcio":"2023-01-02 15:15:00","Data Fim":"2023-01-02 15:20:00","Dura\u00e7\u00e3o do Ciclo":"5min","M\u00e1xima D\u00edvida do Ciclo":-88.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-310.67,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-329.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":5,"Data In\u00edcio":"2023-01-02 15:51:00","Data Fim":"2023-01-02 16:52:00","Dura\u00e7\u00e3o do Ciclo":"1h 1min","M\u00e1xima D\u00edvida do Ciclo":-112.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-255.0,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-304.5,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":6,"Data In\u00edcio":"2023-01-03 09:29:00","Data Fim":"2023-01-03 11:03:00","Dura\u00e7\u00e3o do Ciclo":"1h 34min","M\u00e1xima D\u00edvida do Ciclo":-611.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-226.4,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-280.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":7,"Data In\u00edcio":"2023-01-03 11:05:00","Data Fim":"2023-01-03 11:41:00","Dura\u00e7\u00e3o do Ciclo":"36min","M\u00e1xima D\u00edvida do Ciclo":-199.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-290.5,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-353.5,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":8,"Data In\u00edcio":"2023-01-03 12:07:00","Data Fim":"2023-01-03 12:16:00","Dura\u00e7\u00e3o do Ciclo":"9min","M\u00e1xima D\u00edvida do Ciclo":-163.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-277.43,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-329.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":9,"Data In\u00edcio":"2023-01-03 12:34:00","Data Fim":"2023-01-03 16:45:00","Dura\u00e7\u00e3o do Ciclo":"4h 11min","M\u00e1xima D\u00edvida do Ciclo":-621.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-263.12,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-304.5,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":10,"Data In\u00edcio":"2023-01-03 16:59:00","Data Fim":"2023-01-04 10:07:00","Dura\u00e7\u00e3o do Ciclo":"17h 8min","M\u00e1xima D\u00edvida do Ciclo":-333.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-302.89,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-378.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":11,"Data In\u00edcio":"2023-01-04 10:21:00","Data Fim":"2023-01-04 10:40:00","Dura\u00e7\u00e3o do Ciclo":"19min","M\u00e1xima D\u00edvida do Ciclo":-248.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-305.9,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-366.75,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":12,"Data In\u00edcio":"2023-01-04 12:04:00","Data Fim":"2023-01-05 12:12:00","Dura\u00e7\u00e3o do Ciclo":"1d 8min","M\u00e1xima D\u00edvida do Ciclo":-977.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-300.64,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-355.5,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":13,"Data In\u00edcio":"2023-01-05 14:19:00","Data Fim":"2023-01-05 14:25:00","Dura\u00e7\u00e3o do Ciclo":"6min","M\u00e1xima D\u00edvida do Ciclo":-68.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-357.0,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-436.25,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":14,"Data In\u00edcio":"2023-01-05 14:46:00","Data Fim":"2023-01-05 15:39:00","Dura\u00e7\u00e3o do Ciclo":"53min","M\u00e1xima D\u00edvida do Ciclo":-223.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-334.77,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-378.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":15,"Data In\u00edcio":"2023-01-05 16:16:00","Data Fim":"2023-01-05 16:23:00","Dura\u00e7\u00e3o do Ciclo":"7min","M\u00e1xima D\u00edvida do Ciclo":-78.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-326.79,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-366.75,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":16,"Data In\u00edcio":"2023-01-05 17:30:00","Data Fim":"2023-01-05 17:33:00","Dura\u00e7\u00e3o do Ciclo":"3min","M\u00e1xima D\u00edvida do Ciclo":-58.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-310.2,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-355.5,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":17,"Data In\u00edcio":"2023-01-06 09:39:00","Data Fim":"2023-01-06 09:50:00","Dura\u00e7\u00e3o do Ciclo":"11min","M\u00e1xima D\u00edvida do Ciclo":-93.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-294.44,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-344.25,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":18,"Data In\u00edcio":"2023-01-06 10:05:00","Data Fim":"2023-01-06 10:30:00","Dura\u00e7\u00e3o do Ciclo":"25min","M\u00e1xima D\u00edvida do Ciclo":-224.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-282.59,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-333.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":19,"Data In\u00edcio":"2023-01-06 10:40:00","Data Fim":"2023-01-09 11:24:00","Dura\u00e7\u00e3o do Ciclo":"3d 44min","M\u00e1xima D\u00edvida do Ciclo":-608.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-279.33,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-319.75,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":20,"Data In\u00edcio":"2023-01-09 11:40:00","Data Fim":"2023-01-10 10:45:00","Dura\u00e7\u00e3o do Ciclo":"23h 5min","M\u00e1xima D\u00edvida do Ciclo":-410.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-296.63,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-355.5,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":21,"Data In\u00edcio":"2023-01-10 11:32:00","Data Fim":"2023-01-10 13:34:00","Dura\u00e7\u00e3o do Ciclo":"2h 2min","M\u00e1xima D\u00edvida do Ciclo":-222.0,"M\u00e9dia M\u00e1ximas At\u00e9 o Ciclo":-302.3,"Percentil 75 M\u00e1ximas At\u00e9 o Ciclo":-386.0,"ops_declinio_total":0,"emprestimos_declinio":0,"amortizacoes_declinio":0,"lucros_declinio":0,"ops_recuperacao_total":0,"emprestimos_recuperacao":0,"amortizacoes_recuperacao":0,"lucros_recuperacao":0},{"ID Ciclo":22,"Data In\u00edcio":"2023-01-10 13:56:00","Data Fim":"2023-01-10 13:56:00","D
